name: iOS Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Bạn có thể thay đổi phiên bản Flutter tại đây
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: cd ios && pod install

      - name: Build iOS (No Sign)
        run: flutter build ios --release --no-codesign

      # Bước này sẽ nén thư mục Build để bạn có thể tải về kiểm tra
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos
